version: '3.2'
services:
  portainer_agent:
    image: localhost:15000/portainer-agent
    container_name: portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    network_mode: "host"
    environment:
      - PORTAINER_API_URL=http://127.0.0.1:9000
      - PORTAINER_USERNAME=admin
      - PORTAINER_PASSWORD=xxxxx
